# Node docker image with Cypress and Chrome pre-installed
image: cypress/browsers:node12.0.0-chrome73

# Pipeline
stages:
  - install
  - build
  - test

#new
variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"
 
cache:
  key:
    files:
      - package.json
  paths:
    - .npm
    - cache/Cypress
    - node_modules

# Jobs 

install_dependencies:
  stage: install
  script:
    - npm ci

bundle_app:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - build/

e2etest:    
  stage: test
  before_script:
    - npm install -g http-server
    - npm install cypress
  script:
    # start the server in the background
    - npm run start:ci
    - npx cypress cache path
    - npx cypress cache list
    - npm run cypress:verify
    - NODE_ENV=test npm test
    - npx nyc report --reporter=text-summary
  artifacts:
    when: always
    paths:
      # save both cypress artifacts and coverage results
      - coverage
      - cypress/videos/**/*.mp4
      - cypress/screenshots/**/*.png
    expire_in: 10 days
  only: 
    - staging
    - master