# Node docker image with Cypress and Chrome pre-installed
image: cypress/browsers:node12.0.0-chrome73

# Pipeline
stages:
  - install
  - build
  - test

#new
variables:
  yarn_config_cache: "$CI_PROJECT_DIR/.yarn"
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"
 
cache:
  key:
    files:
      - package.json
  paths:
    - .yarn
    - cache/Cypress
    - node_modules


# Jobs 

install_dependencies:
  stage: install
  script:
    - yarn install --frozen-lockfile

bundle_app:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - build/

e2etest:    
  stage: test
  before_script:
    - npm install -g http-server
    - npm install cypress
  script:
    # start the server in the background
    - npm run start:ci